### PR TITLE
Dynamic clustering

### PR DESCRIPTION
**Pull request by BasLangenberg**
**_WARNING: PLEASE DO NOT MERGE**_

Hi Edwin,

This is the promised pull request reflecting our discussion in https://github.com/biemond/biemond-orawls/issues/157

It's much more unstructured than I anticipated, as I updated orawls to the latest version before merging my commit. In the end I think this is the best way to show this to you though.

What I did:
1. Update orawls to last version
2. Added my dynamic targetting logic in wls_server and wls_cluster types
3. Updated your admin hiera file to create a use case

Sadly, I did not manage to successfully test the Vagrant box due to strange ruby/puppet errors. I'll try to look into that later. The purpose of this PR is to share knowledge with you and possibly inspire you. :+1: 

I would love to hear your feedback!

As always, thanks for all your work on the orawls module!

Kind regards,
Bas

### CODE REVIEW

**Comment by biemond** [comment]
Perfect,

I will take a look at it and learn from it also add this to a branch and try it out.

**Comment by BasLangenberg** [comment]
Nice, can't wait for your feedback. :+1: 

Small addedum is that in our 'production' repo, sort-a-like changes are also made for the datasource and mailsession type in order to have the same behaviour.

**Comment by biemond** [comment]
it looks great and I will use it. This way we can support both ways. 
and we need to use the notes fields. I don't see any other good option.

Can you send me a pull request on the orawls repos.

thanks

**Comment by BasLangenberg** [comment]
Thanks for your feedback. I agree that this could be backwards compatible (which was my aim too) and can be merged. It's nice you want to have it, it still feels a bit of a 'hack' to me.

I'll create a PR on the module and add some documentation on it as well. I'll leave this open for the time being for reference.

**Comment by biemond** [comment]
so everything is working again and made a lot of fixes so it should work in all situations

thanks

**Comment by BasLangenberg** [comment]
I just went through them out of curiousity. Hopefully I did not break too much. All was working at my side but my tests are a bit limited.

Thanks Edwin!

**Pull request merged**
